### ISSUE TITLE
intermission

### ISSUE THREAD

**Issue by ghost** [dsverdlo/minqlx-plugins#13]
Hi!

Thanks for all useful plugins!
I don´t know if this is the right forum for wishes or ideas?

I think it would be neat with music on warmups on server as a option.

Regards / popqorn

**Comment by dsverdlo** [comment]
Hey popqorn,

You're very welcome! 
I don't really have a forum, but I, and some other plugin developers can often be found on IRC in #minqlbot and discord.
For further ideas and requests.

I kind of see what you mean. Have some music looping during warmup (and only if there are players on the server, probably). Not sure how this would clash with the 'fun' sounds plugin, though. (Example: there is a song playing and somebody types "hahaha yeah"... The song that was playing would be stopped and cannot be resumed)

Also I don't think the plugin can know when a song or a sound is 'done', and thus when to play the next one...

Kind regards,
iou

**Comment by ghost** [comment]
Hi again!

I always upload remixed 2 minutes long songs. When I load a song !intermission and myself or another uses funnysounds its not interrupt the songs in  anyhow and next time pressing !intermission it is working. Now... time problem. Maybe user could set cvar once 2 minutes or milliseconds =) Its a shame I don´t know anything about .py and don´t know how much work or limits a script has. But if you want to take a look at it  
would be cool to have the future. Then of course all players don´t even has sound enabled so the risk is to work for deaf ears.. But all server owners Maybe can inform server guests about the future.

Well, thanks for the showing interest in my suggest! <3 / popqorn

**Comment by dsverdlo** [comment]
So if you're playing a song, it will also play the funsounds?
The way I could see a possible way of working is encoding the length of a song in the songname itself, so when it is specified in the cvar, the program can deduct the end of the song and when it will be done.
This of course introduces the problem of human error, since it takes some automated calculation away, but it could work, I think.

Kr,

iou
