### ISSUE TITLE
Translate.py !urban not working.

### ISSUE THREAD

**Issue by cgrahame** [dsverdlo/minqlx-plugins#17]
Is it just me or does the !urban and !define commands no longer return a response with the translate.py plugin?

When I use either of those commands (with a word or phrase after it) it just does nothing. Doesn't return any response. I know the plugin is loaded because if I just issue the command without any word or phrase after it it will tell me what the use of the command is.

Any ideas?

**Comment by dsverdlo** [comment]
Hello @cgrahame .

Do you see anything related in the console?
Or any errors in the minqlx.log file on the server?

Maybe a dumb question, but I got to task: is the plugin loaded? (You can verify with !v_translate)

**Comment by cgrahame** [comment]
Hi dsverdlo, 

Yep, the plugin is definitely loaded. If a do a !define or !urban with no word or phrase after the plugin will tell me the proper usage for those commands. !v_translate reports "Currently using iouonegirl's latest translate plugin version v0.13."

One of the first things I checked was the minqlx.log files and it reports no errors. It will show the command being called but no error response or return message from issuing the command. Just get no response from using the !define/!urban commands at all.

They used to work but I hadn't tried them (!define/!urban) in several months and tried to use that command just recently and found it gave no reply or error.

I did recently about 5 months ago move my servers to a new dedicated server and had to re-setup everything and I think this is the first time I have tried to use the translate plugin since then, so I'm not sure if it is something related to how the new server is setup. 

The server is running the same OS (Ubuntu 16.04 lts) as the old server and everything else works just fine.

Just confused as to why the !define command in the translate plugin no longer gives any reply or any error message. Just nothing like the command is being ignored.

**Comment by dsverdlo** [comment]
Apparently RapidAPI bought Mashape (API marketplace) and the link for urban needed to be updated. Can you try to update the translate plugin to version v0.14?

> You can do this with: !update translate

Let me know if it's fixed :-)

**Comment by cgrahame** [comment]
I updated the translate plugin to version v0.14 and tried it but I get the same thing. Doesn't give any response when using either !define or !urban when there is a word or phrase put after one of those commands. If I type the command on its own it will tell me the proper usage for the command.

Just strange that it gives no response, error or anything. Nothing in the logs.

I am assuming that if it works for you then it must be something to do with my own setup. Just strange that it only seems to be affecting this one plugin and nothing else.

**Comment by cgrahame** [comment]
So.... I spent some time adding some debugging code into the translate.py plugin in the form of self.msg("") calls in various places to determine where the code is breaking for me when using the !urban command.

I'm not a programmer and I only have a rudimentary understanding of Python but I did determine that the problem lies in the help_callback_urban function at line 455. Specifically it seems to be the code at line 464.

**if results['result_type'] != "no_results":**

It seems that there is no 'result_type' returned at all in results.

I changed line 464 to -

**if results['list'] != []:**

And now the !urban command works as expected.

I also found an error on line 473 in the code -

**msg("{}No urban dict results found for: ".format(C, query))**

Pretty sure you left off some curly brackets? Should be -

**msg("{}No urban dict results found for: {}".format(C, query))**

Like I said, I am no programmer and only have a basic understanding of Python but these few changes seem to have fixed my issue with the !urban command not working with the Translate plugin. 

No idea why it just stopped working because it used to work fine without these changes.

**Comment by dsverdlo** [comment]
Hey, that's a nice catch!

To be completely honest, I'm quite busy these days and did not fully test the 'fix' thoroughly.
I assumed fixing the API key would have been sufficient.

I'm glad you got it working, thanks for sharing your findings!
I'll look into it and release a tested v0.15 sometime this week

It stopped working because they completely changed the way their API worked. We needed to send a different key to a different link and got a different reply than before.

**Comment by cgrahame** [comment]
All good. Thanks for putting in the time making these plugins in the first place and making them available to all us server admins. Much appreciated.
